/* GLava bars module — generated by matugen.
 * Colors derived from the Material Design 3 palette. */

/* Bar dimensions */
#define BAR_WIDTH 4
#define BAR_GAP 2
#define C_LINE 1

/* Bar outline */
#define BAR_OUTLINE {{colors.outline.default.hex}}
#define BAR_OUTLINE_WIDTH 0

/* Amplification and gradient */
#define AMPLIFY 300
#define GRADIENT_POWER 60
#define GRADIENT (d / GRADIENT_POWER + 1)

/* Bar color — primary accent from wallpaper palette. */
#define COLOR ({{colors.primary.default.hex}} * GRADIENT)

/* Alpha support for native compositor transparency. */
#define USE_ALPHA 1

/* Layout */
#define DIRECTION 0
#define INVERT 0
#define FLIP 0
#define MIRROR_YX 0
