/* GLava bars module configuration — generated by matugen.
 * Colors are derived from the Material Design 3 palette. */

/* Color of the bars (GLSL vec4: r, g, b, a). */
#define COLOR {{colors.primary.default.hex}}
#define OUTLINE {{colors.primary_container.default.hex}}

/* Number of bars and smoothing. */
#define BAR_WIDTH 4
#define BAR_GAP 2
#define BAR_FILTER_FIRST_ORDER true
#define BAR_FILTER_FIRST_ORDER_FACTOR 0.15

/* Gravity and responsiveness. */
#define GRAVITY 4.0
#define GRADIENT 0.75

/* Background — transparent, composited by niri. */
#define BACKGROUND {{colors.background.default.hex}}00
