font=FiraMono Nerd Font 11
background-color={{colors.background.default.hex}}cc
text-color={{colors.on_background.default.hex}}
border-color={{colors.primary.default.hex}}
border-size=1
border-radius=8
padding=8
default-timeout=6000

[urgency=high]
border-color={{colors.error.default.hex}}
default-timeout=0
