-- Generated by matugen — do not edit manually.
-- Neovim highlight overrides using M3 hex colors from the current wallpaper palette.
-- See home/ethel/matugen/templates/ghostty-colors.conf for the M3 role reference.

-- ---------------------------------------------------------------------------
-- Core UI
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "CursorLine", { bg = "{{colors.surface_container_high.default.hex}}" })
vim.api.nvim_set_hl(0, "Visual", { bg = "{{colors.secondary_container.default.hex}}" })
vim.api.nvim_set_hl(0, "Folded", { bg = "{{colors.surface_bright.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" })

-- ===========================================================================
-- Generic treesitter syntax — applies to all languages
-- ===========================================================================
-- Accent mapping: primary = keywords, secondary = functions, tertiary = types.
-- All foreground colors use tone-80+ roles for readability on dark backgrounds.

-- ---------------------------------------------------------------------------
-- Keywords (primary — control flow, the skeleton of code)
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@keyword", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = "{{colors.primary.default.hex}}" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@keyword.exception", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@keyword.import", { fg = "{{colors.primary.default.hex}}" })
vim.api.nvim_set_hl(0, "@keyword.coroutine", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@keyword.modifier", { fg = "{{colors.primary.default.hex}}", italic = true })

-- ---------------------------------------------------------------------------
-- Functions (secondary — callable things)
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@function", { fg = "{{colors.secondary.default.hex}}" })
vim.api.nvim_set_hl(0, "@function.call", { fg = "{{colors.secondary.default.hex}}" })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = "{{colors.secondary.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@function.method", { fg = "{{colors.secondary.default.hex}}" })
vim.api.nvim_set_hl(0, "@function.method.call", { fg = "{{colors.secondary.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Types (tertiary — the type system)
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@type", { fg = "{{colors.tertiary.default.hex}}" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "{{colors.tertiary.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@type.definition", { fg = "{{colors.tertiary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@constructor", { fg = "{{colors.tertiary.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Strings (tertiary_fixed_dim — data, distinct from code)
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@string", { fg = "{{colors.tertiary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@string.escape", { fg = "{{colors.tertiary_fixed.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@string.special", { fg = "{{colors.tertiary_fixed.default.hex}}" })
vim.api.nvim_set_hl(0, "@string.regex", { fg = "{{colors.tertiary_fixed.default.hex}}" })
vim.api.nvim_set_hl(0, "@character", { fg = "{{colors.tertiary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@character.special", { fg = "{{colors.tertiary_fixed.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Constants & literals (secondary_fixed_dim — stable values)
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@constant", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = "{{colors.secondary_fixed_dim.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@boolean", { fg = "{{colors.secondary_fixed_dim.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@number", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@number.float", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Variables — default readable text, builtins/params slightly muted
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@variable", { fg = "{{colors.on_surface.default.hex}}" })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "{{colors.on_surface_variant.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = "{{colors.on_surface_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@variable.member", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Operators & punctuation — fully visible, never miss a semicolon
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@operator", { fg = "{{colors.on_surface.default.hex}}" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = "{{colors.on_surface.default.hex}}" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = "{{colors.on_surface.default.hex}}" })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = "{{colors.on_surface.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Comments — low emphasis, special annotations highlighted
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@comment", { fg = "{{colors.outline.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@comment.todo", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@comment.note", { fg = "{{colors.secondary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@comment.warning", { fg = "{{colors.tertiary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@comment.error", { fg = "{{colors.error.default.hex}}", bold = true })

-- ---------------------------------------------------------------------------
-- Properties & attributes — object fields
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@property", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@attribute", { fg = "{{colors.secondary_fixed_dim.default.hex}}", italic = true })

-- ---------------------------------------------------------------------------
-- Tags (HTML/JSX) — primary for elements, muted for attributes
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@tag", { fg = "{{colors.primary.default.hex}}" })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Labels & modules
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@label", { fg = "{{colors.secondary.default.hex}}" })
vim.api.nvim_set_hl(0, "@module", { fg = "{{colors.on_surface_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@module.builtin", { fg = "{{colors.on_surface_variant.default.hex}}", italic = true })

-- ---------------------------------------------------------------------------
-- Generic markup (markdown, etc.)
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@markup.heading", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@markup.strong", { fg = "{{colors.on_surface.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@markup.italic", { fg = "{{colors.on_surface.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@markup.link", { fg = "{{colors.primary.default.hex}}", underline = true })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = "{{colors.secondary_fixed_dim.default.hex}}", underline = true })
vim.api.nvim_set_hl(0, "@markup.raw", { fg = "{{colors.tertiary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@markup.list", { fg = "{{colors.primary.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Diff
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@diff.plus", { fg = "{{colors.tertiary.default.hex}}" })
vim.api.nvim_set_hl(0, "@diff.minus", { fg = "{{colors.error.default.hex}}" })
vim.api.nvim_set_hl(0, "@diff.delta", { fg = "{{colors.secondary.default.hex}}" })

-- ===========================================================================
-- Org-mode
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Org-mode headlines (headlines.nvim)
-- ---------------------------------------------------------------------------
-- Background bars: uniform surface_bright (~tone 24) — subtle lift from base.
vim.api.nvim_set_hl(0, "Headline1", { bg = "{{colors.surface_bright.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline2", { bg = "{{colors.surface_bright.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline3", { bg = "{{colors.surface_bright.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline4", { bg = "{{colors.surface_bright.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline5", { bg = "{{colors.surface_bright.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline6", { bg = "{{colors.surface_bright.default.hex}}" })

-- Headline text: tone ~80 accent roles only — never _container tokens (tone ~30).
-- Each level uses a distinct hue for visual hierarchy. All foregrounds are
-- bright enough to exceed WCAG AA 4.5:1 contrast on surface backgrounds.
vim.api.nvim_set_hl(0, "@org.headline.level1", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level2", { fg = "{{colors.secondary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level3", { fg = "{{colors.tertiary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level4", { fg = "{{colors.error.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level5", { fg = "{{colors.primary_fixed_dim.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level6", { fg = "{{colors.tertiary_fixed_dim.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level7", { fg = "{{colors.on_surface_variant.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level8", { fg = "{{colors.secondary_fixed.default.hex}}", bold = true })

-- ---------------------------------------------------------------------------
-- TODO keywords
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.keyword.todo", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.keyword.done", { fg = "{{colors.on_surface_variant.default.hex}}", bold = true, strikethrough = true })

-- ---------------------------------------------------------------------------
-- Priority
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.priority.highest", { fg = "{{colors.error.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.priority.high", { fg = "{{colors.tertiary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.priority.default", { fg = "{{colors.secondary.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.priority.low", { fg = "{{colors.on_surface_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.priority.lowest", { fg = "{{colors.outline.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Timestamps
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.timestamp.active", { fg = "{{colors.tertiary.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.timestamp.inactive", { fg = "{{colors.outline.default.hex}}", italic = true })

-- ---------------------------------------------------------------------------
-- Markup — content uses readable tone-80+ roles, delimiters are muted
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.bold", { fg = "{{colors.on_surface.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.bold.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.italic", { fg = "{{colors.on_surface.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@org.italic.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.underline", { fg = "{{colors.on_surface.default.hex}}", underline = true })
vim.api.nvim_set_hl(0, "@org.underline.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.strikethrough", { fg = "{{colors.outline.default.hex}}", strikethrough = true })
vim.api.nvim_set_hl(0, "@org.strikethrough.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.code", { fg = "{{colors.tertiary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.code.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.verbatim", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.verbatim.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Links
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.hyperlink", { fg = "{{colors.primary.default.hex}}", underline = true })
vim.api.nvim_set_hl(0, "@org.hyperlink.desc", { fg = "{{colors.primary.default.hex}}", underline = true })
vim.api.nvim_set_hl(0, "@org.hyperlink.url", { fg = "{{colors.primary_container.default.hex}}", underline = true })
vim.api.nvim_set_hl(0, "@org.footnote", { fg = "{{colors.primary_container.default.hex}}", underline = true })

-- ---------------------------------------------------------------------------
-- Lists & checkboxes
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.bullet", { fg = "{{colors.primary.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.checkbox", { fg = "{{colors.outline.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.checkbox.halfchecked", { fg = "{{colors.secondary.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.checkbox.checked", { fg = "{{colors.tertiary.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Blocks
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.block", { fg = "{{colors.on_surface_variant.default.hex}}", italic = true })

-- ---------------------------------------------------------------------------
-- Properties & drawers — metadata, low emphasis
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.properties", { fg = "{{colors.outline.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.properties.name", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.drawer", { fg = "{{colors.outline.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.table.delimiter", { fg = "{{colors.outline_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.table.heading", { fg = "{{colors.primary.default.hex}}", bold = true })

-- ---------------------------------------------------------------------------
-- Tags, plan, comments, directives
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.tag", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.plan", { fg = "{{colors.tertiary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.comment", { fg = "{{colors.outline.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@org.directive", { fg = "{{colors.outline.default.hex}}", italic = true })

-- ---------------------------------------------------------------------------
-- LaTeX / math
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.latex", { fg = "{{colors.tertiary.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.latex_env", { fg = "{{colors.tertiary_fixed_dim.default.hex}}" })

-- ---------------------------------------------------------------------------
-- Agenda buffer
-- ---------------------------------------------------------------------------
vim.api.nvim_set_hl(0, "@org.agenda.deadline", { fg = "{{colors.error.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.agenda.scheduled", { fg = "{{colors.tertiary.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.agenda.scheduled_past", { fg = "{{colors.secondary.default.hex}}", italic = true })
vim.api.nvim_set_hl(0, "@org.agenda.header", { fg = "{{colors.primary.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.agenda.today", { fg = "{{colors.primary.default.hex}}", bold = true, underline = true })
vim.api.nvim_set_hl(0, "@org.agenda.weekend", { fg = "{{colors.on_surface_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.agenda.tag", { fg = "{{colors.secondary_fixed_dim.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.agenda.separator", { fg = "{{colors.outline_variant.default.hex}}" })
vim.api.nvim_set_hl(0, "@org.agenda.time_grid", { fg = "{{colors.outline.default.hex}}" })
