# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-73221839-dce9-4f90-8bd6-70573ea43cd8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-73221839-dce9-4f90-8bd6-70573ea43cd8".device = "/dev/disk/by-uuid/73221839-dce9-4f90-8bd6-70573ea43cd8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/237A-52C5";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-9de9918d-99aa-4f0d-8a35-22af09cf8049";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
