# Browsing home workflow — qutebrowser, web apps, keymap.py generation.
{
  config,
  pkgs,
  lib,
  dotfilesDir,
  ...
}: let
  homeLib = import ../lib.nix {inherit lib pkgs config;};
  inherit (homeLib) mkDesktopFile;

  layouts = import ../core/keymap-layouts.nix;

  # ── Qutebrowser keymap.py generation ──────────────────────────────────
  # Maps non-Latin → Latin so keybindings work regardless of active layout.

  allPairs = lib.concatLists (lib.mapAttrsToList (_name: layout:
    (lib.mapAttrsToList (from: to: {inherit from to;}) layout.lower)
    ++ (lib.mapAttrsToList (from: to: {inherit from to;}) layout.upper)
    ++ (lib.mapAttrsToList (from: to: {inherit from to;}) layout.punctuation.lower)
    ++ (lib.mapAttrsToList (from: to: {inherit from to;}) layout.punctuation.upper))
  layouts);

  pyEscape = c:
    if c == "'"
    then "\\'"
    else if c == "\\"
    then "\\\\"
    else c;

  pyEntries = lib.concatStringsSep "\n" (map (p: "    '${pyEscape p.from}': '${pyEscape p.to}',") allPairs);

  qutebrowserKeymapPy = ''
    # Generated by modules/home/workflows/browsing.nix — do not edit.
    # Maps non-Latin keys to Latin equivalents so keybindings work
    # regardless of active keyboard layout.
    c.bindings.key_mappings = {
    ${pyEntries}
    }
  '';

  # ── Web apps ──────────────────────────────────────────────────────────
  webApps = [
    {
      name = "YouTube";
      url = "https://www.youtube.com";
      icon = "video-x-generic";
    }
    {
      name = "Nix Packages Search";
      url = "https://search.nixos.org/packages";
      icon = "system-software-install";
    }
    {
      name = "Neuro Karaoke";
      url = "https://neurokaraoke.com";
      icon = "audio-x-generic";
    }
  ];

  # ── Apple Music launcher script ───────────────────────────────────────
  appleMusic = pkgs.writeShellApplication {
    name = "apple-music";
    runtimeInputs = [pkgs.chromium];
    text = ''
      exec chromium \
        --app=https://music.apple.com \
        --class=webapp-Apple-Music \
        --name=webapp-Apple-Music \
        --ozone-platform=wayland \
        --enable-features=WaylandWindowDecorations
    '';
  };
in {
  home.packages = [
    pkgs.qutebrowser
    pkgs.chromium
    appleMusic
  ];

  home.sessionVariables.BROWSER = "qutebrowser";
  xdg.configFile."qutebrowser/config.py".source = dotfilesDir + "/qutebrowser/config.py";
  xdg.configFile."qutebrowser/keymap.py".text = qutebrowserKeymapPy;

  # Default browser — MIME associations.
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = "org.qutebrowser.qutebrowser.desktop";
      "x-scheme-handler/http" = "org.qutebrowser.qutebrowser.desktop";
      "x-scheme-handler/https" = "org.qutebrowser.qutebrowser.desktop";
      "x-scheme-handler/chrome" = "org.qutebrowser.qutebrowser.desktop";
      "application/xhtml+xml" = "org.qutebrowser.qutebrowser.desktop";
      "application/x-extension-htm" = "org.qutebrowser.qutebrowser.desktop";
      "application/x-extension-html" = "org.qutebrowser.qutebrowser.desktop";
      "application/x-extension-shtml" = "org.qutebrowser.qutebrowser.desktop";
      "application/x-extension-xhtml" = "org.qutebrowser.qutebrowser.desktop";
      "application/x-extension-xht" = "org.qutebrowser.qutebrowser.desktop";
    };
  };

  # Declarative web apps (Chromium app mode).
  home.file = builtins.listToAttrs (map mkDesktopFile webApps);
}
