# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-51ed2edf-5656-4d33-a902-8de42bfe5d8a";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."luks-51ed2edf-5656-4d33-a902-8de42bfe5d8a".device = "/dev/disk/by-uuid/51ed2edf-5656-4d33-a902-8de42bfe5d8a";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C442-ECED";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-0b2a9ed9-2091-4849-b367-fb30b81362da";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-0b2a9ed9-2091-4849-b367-fb30b81362da".device = "/dev/disk/by-uuid/0b2a9ed9-2091-4849-b367-fb30b81362da";

  swapDevices = [
    {device = "/dev/mapper/luks-0de2bb84-adb6-4580-83df-dfd1459ad438";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
