/* GLava main configuration.
 * Selects the bars visualizer module and sets window/audio behavior.
 * Colors live in bars.glsl, generated by matugen. */

#request mod bars

/* Window hints — niri rules handle floating/positioning,
   but we still disable decorations for a clean overlay. */
#request setfloating  false
#request setdecorated false
#request setfocused   false
#request setmaximized false

/* Transparent background — composited by niri. */
#request setopacity "native"

/* Window title and geometry (niri rules refine positioning). */
#request settitle "GLava"
#request setgeometry 0 0 1920 180
#request setbg 00000000

/* Audio source — auto-detect PipeWire/PulseAudio default output. */
#request setsource "auto"
#request setmirror false

/* Rendering — vsync on, no frame limiter, interpolation for smoothness. */
#request setswap 1
#request setframerate 0
#request setinterpolate true

/* Pause rendering when a fullscreen app is focused. */
#request setfullscreencheck true

/* Silence framerate logging. */
#request setprintframes false

/* Audio buffer tuning. */
#request setsamplesize 1024
#request setbufsize 4096
#request setsamplerate 22050

/* OpenGL version. */
#request setversion 3 3
#request setshaderversion 330
