/* GLava main configuration.
 * Based on the full default config — GLava segfaults if directives are missing.
 * Selects the bars visualizer module and sets window/audio behavior.
 * Colors live in bars.glsl, generated by matugen. */

#request mod bars

/* Window hints — niri rules handle floating/positioning,
   but we disable decorations for a clean overlay. */
#request setfloating  false
#request setdecorated false
#request setfocused   false
#request setmaximized false

/* Transparent background — composited by niri. */
#request setopacity "native"

/* Mirror left and right audio channels. */
#request setmirror false

/* OpenGL context versions — do not change. */
#request setversion 3 3
#request setshaderversion 330

/* Window title and geometry (niri rules refine positioning). */
#request settitle "GLava"
#request setgeometry 0 0 1920 180
#request setbg 00000000

/* X11 window type — normal window, niri rules handle the rest. */
#request setxwintype "normal"

/* Click-through disabled (niri manages focus). */
#request setclickthrough false

/* Audio source — auto-detect PipeWire/PulseAudio default output. */
#request setsource "auto"

/* Vsync swap interval. */
#request setswap 1

/* Interpolation for smooth visuals at lower update rates. */
#request setinterpolate true

/* No frame limiter — vsync handles it. */
#request setframerate 0

/* Pause rendering when a fullscreen app is focused. */
#request setfullscreencheck true

/* Silence framerate logging. */
#request setprintframes false

/* Audio buffer tuning. */
#request setsamplesize 1024
#request setbufsize 4096
#request setsamplerate 22050

/* Deprecated options — required to prevent segfault. */
#request setforcegeometry false
#request setforceraised false
#request setbufscale 1
