/* GLava main configuration.
 * Selects the bars visualizer module and sets window/audio behavior.
 * Colors live in bars.glsl, generated by matugen. */

/* Visualizer module — bars is a classic spectrum analyzer. */
#request mod bars

/* Use PulseAudio (PipeWire compat layer) as the audio source. */
#request setpulseaudio

/* Transparent background — composited by niri. */
#request setopacity "native"
#request setdecorate false

/* Framerate cap. */
#request setframerate 60

/* Force window geometry via GLava (niri rules handle positioning). */
#request setgeometry 0 0 1920 180

/* Fullscreen off — we want a floating overlay, not a desktop embed. */
#request setfullscreencheck false

/* Mirror left and right audio channels for a symmetric look. */
#request setmirror false
