-- Generated by matugen — do not edit manually.
-- Neovim highlight overrides using M3 hex colors from the current wallpaper palette.
-- See home/ovg/matugen/templates/ghostty-colors.conf for the M3 role reference.

-- ---------------------------------------------------------------------------
-- Org-mode headlines (headlines.nvim)
-- ---------------------------------------------------------------------------
-- Background bars: container tones (~30) — dim accent fills.
vim.api.nvim_set_hl(0, "Headline1", { bg = "{{colors.primary_container.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline2", { bg = "{{colors.secondary_container.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline3", { bg = "{{colors.tertiary_container.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline4", { bg = "{{colors.error_container.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline5", { bg = "{{colors.surface_container_high.default.hex}}" })
vim.api.nvim_set_hl(0, "Headline6", { bg = "{{colors.surface_bright.default.hex}}" })

-- Headline text: tone ~80 roles — bright accent foregrounds.
vim.api.nvim_set_hl(0, "@org.headline.level1", { fg = "{{colors.primary.default.hex}}",            bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level2", { fg = "{{colors.primary_container.default.hex}}",  bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level3", { fg = "{{colors.tertiary_container.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level4", { fg = "{{colors.error.default.hex}}",              bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level5", { fg = "{{colors.secondary.default.hex}}",          bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level6", { fg = "{{colors.tertiary.default.hex}}",           bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level7", { fg = "{{colors.on_surface_variant.default.hex}}", bold = true })
vim.api.nvim_set_hl(0, "@org.headline.level8", { fg = "{{colors.secondary_container.default.hex}}", bold = true })

-- Links
vim.api.nvim_set_hl(0, "@org.hyperlink",      { fg = "{{colors.primary.default.hex}}",           underline = true })
vim.api.nvim_set_hl(0, "@org.hyperlink.desc", { fg = "{{colors.primary.default.hex}}",           underline = true })
vim.api.nvim_set_hl(0, "@org.hyperlink.url",  { fg = "{{colors.primary_container.default.hex}}", underline = true })
