-- Generated by matugen — do not edit manually.
-- Lualine theme using M3 hex colors from the current wallpaper palette.
-- Gradient rule: a.bg (accent, ~80) → b (surface_bright, ~24) → c (surface_container, ~12).
--   a.fg = c.bg, c.fg = b.bg  (powerline stepping)
return {
  normal = {
    a = { bg = "{{colors.primary.default.hex}}",            fg = "{{colors.surface_container.default.hex}}", gui = "bold" },
    b = { bg = "{{colors.surface_bright.default.hex}}",     fg = "{{colors.primary.default.hex}}" },
    c = { bg = "{{colors.surface_container.default.hex}}",  fg = "{{colors.surface_bright.default.hex}}" },
  },
  insert = {
    a = { bg = "{{colors.tertiary.default.hex}}",           fg = "{{colors.surface_container.default.hex}}", gui = "bold" },
    b = { bg = "{{colors.surface_bright.default.hex}}",     fg = "{{colors.tertiary.default.hex}}" },
    c = { bg = "{{colors.surface_container.default.hex}}",  fg = "{{colors.surface_bright.default.hex}}" },
  },
  visual = {
    a = { bg = "{{colors.secondary.default.hex}}",          fg = "{{colors.surface_container.default.hex}}", gui = "bold" },
    b = { bg = "{{colors.surface_bright.default.hex}}",     fg = "{{colors.secondary.default.hex}}" },
    c = { bg = "{{colors.surface_container.default.hex}}",  fg = "{{colors.surface_bright.default.hex}}" },
  },
  replace = {
    a = { bg = "{{colors.tertiary_fixed.default.hex}}",     fg = "{{colors.surface_container.default.hex}}", gui = "bold" },
    b = { bg = "{{colors.surface_bright.default.hex}}",     fg = "{{colors.tertiary_fixed.default.hex}}" },
    c = { bg = "{{colors.surface_container.default.hex}}",  fg = "{{colors.surface_bright.default.hex}}" },
  },
  command = {
    a = { bg = "{{colors.error.default.hex}}",              fg = "{{colors.surface_container.default.hex}}", gui = "bold" },
    b = { bg = "{{colors.surface_bright.default.hex}}",     fg = "{{colors.error.default.hex}}" },
    c = { bg = "{{colors.surface_container.default.hex}}",  fg = "{{colors.surface_bright.default.hex}}" },
  },
  inactive = {
    a = { bg = "{{colors.surface_bright.default.hex}}",     fg = "{{colors.surface_container.default.hex}}" },
    b = { bg = "{{colors.surface_container.default.hex}}",  fg = "{{colors.on_surface_variant.default.hex}}" },
    c = { bg = "{{colors.on_surface_variant.default.hex}}", fg = "{{colors.surface_container.default.hex}}" },
  },
}
