# Generated by matugen — do not edit. Source: qutebrowser-colors.py template.

bg        = "{{colors.background.default.hex}}"
fg        = "{{colors.on_background.default.hex}}"
accent    = "{{colors.primary.default.hex}}"
header_bg = "{{colors.surface_variant.default.hex}}"
card_bg   = "{{colors.secondary_container.default.hex}}"
red       = "{{colors.error.default.hex}}"
warn      = "{{colors.tertiary_container.default.hex}}"
green     = "{{colors.primary_container.default.hex}}"
purple    = "{{colors.tertiary.default.hex}}"

# Completion
c.colors.completion.fg                          = fg
c.colors.completion.odd.bg                      = bg
c.colors.completion.even.bg                     = card_bg
c.colors.completion.category.fg                 = accent
c.colors.completion.category.bg                 = header_bg
c.colors.completion.category.border.top         = header_bg
c.colors.completion.category.border.bottom      = header_bg
c.colors.completion.item.selected.fg            = fg
c.colors.completion.item.selected.bg            = accent
c.colors.completion.item.selected.border.top    = accent
c.colors.completion.item.selected.border.bottom = accent
c.colors.completion.match.fg                    = accent
c.colors.completion.scrollbar.fg                = fg
c.colors.completion.scrollbar.bg                = header_bg

# Downloads bar
c.colors.downloads.bar.bg   = bg
c.colors.downloads.start.fg = fg
c.colors.downloads.start.bg = accent
c.colors.downloads.stop.fg  = fg
c.colors.downloads.stop.bg  = card_bg
c.colors.downloads.error.fg = red

# Hints (link-follow overlay)
c.colors.hints.fg       = bg
c.colors.hints.bg       = accent
c.colors.hints.match.fg = fg

# Key hint overlay
c.colors.keyhint.fg        = fg
c.colors.keyhint.bg        = header_bg
c.colors.keyhint.suffix.fg = accent

# Messages
c.colors.messages.error.bg      = red
c.colors.messages.error.border  = red
c.colors.messages.error.fg      = fg
c.colors.messages.warning.bg     = warn
c.colors.messages.warning.border = warn
c.colors.messages.warning.fg     = bg
c.colors.messages.info.bg        = header_bg
c.colors.messages.info.border    = header_bg
c.colors.messages.info.fg        = fg

# Prompts
c.colors.prompts.bg          = header_bg
c.colors.prompts.border      = f"1px solid {accent}"
c.colors.prompts.fg          = fg
c.colors.prompts.selected.bg = accent
c.colors.prompts.selected.fg = fg

# Status bar
c.colors.statusbar.normal.bg           = bg
c.colors.statusbar.normal.fg           = fg
c.colors.statusbar.insert.bg           = accent
c.colors.statusbar.insert.fg           = fg
c.colors.statusbar.passthrough.bg      = purple
c.colors.statusbar.passthrough.fg      = fg
c.colors.statusbar.private.bg          = card_bg
c.colors.statusbar.private.fg          = fg
c.colors.statusbar.command.bg          = header_bg
c.colors.statusbar.command.fg          = fg
c.colors.statusbar.command.private.bg  = card_bg
c.colors.statusbar.command.private.fg  = fg
c.colors.statusbar.caret.bg            = purple
c.colors.statusbar.caret.fg            = fg
c.colors.statusbar.caret.selection.bg  = purple
c.colors.statusbar.caret.selection.fg  = fg
c.colors.statusbar.progress.bg         = accent
c.colors.statusbar.url.fg              = fg
c.colors.statusbar.url.error.fg        = red
c.colors.statusbar.url.hover.fg        = accent
c.colors.statusbar.url.success.http.fg  = warn
c.colors.statusbar.url.success.https.fg = green
c.colors.statusbar.url.warn.fg          = warn

# Tabs
c.colors.tabs.bar.bg                  = header_bg
c.colors.tabs.odd.fg                  = fg
c.colors.tabs.odd.bg                  = header_bg
c.colors.tabs.even.fg                 = fg
c.colors.tabs.even.bg                 = bg
c.colors.tabs.selected.odd.fg         = fg
c.colors.tabs.selected.odd.bg         = accent
c.colors.tabs.selected.even.fg        = fg
c.colors.tabs.selected.even.bg        = accent
c.colors.tabs.pinned.odd.fg           = fg
c.colors.tabs.pinned.odd.bg           = header_bg
c.colors.tabs.pinned.even.fg          = fg
c.colors.tabs.pinned.even.bg          = bg
c.colors.tabs.pinned.selected.odd.fg  = fg
c.colors.tabs.pinned.selected.odd.bg  = accent
c.colors.tabs.pinned.selected.even.fg = fg
c.colors.tabs.pinned.selected.even.bg = accent
