# Generated by matugen — do not edit. Source: qutebrowser-colors.py template.

# Surface / background
bg         = "{{colors.surface_container_lowest.default.hex}}"
surface    = "{{colors.surface_container_low.default.hex}}"
surface_hi = "{{colors.surface_container.default.hex}}"
surface_br = "{{colors.surface_bright.default.hex}}"

# Foreground
fg         = "{{colors.on_surface.default.hex}}"
fg_dim     = "{{colors.on_surface_variant.default.hex}}"

# Accent
accent     = "{{colors.primary.default.hex}}"
on_accent  = "{{colors.on_primary.default.hex}}"

# Semantic
red        = "{{colors.error.default.hex}}"
on_red     = "{{colors.on_error.default.hex}}"
red_ctr    = "{{colors.error_container.default.hex}}"
warn       = "{{colors.tertiary.default.hex}}"
green      = "{{colors.primary.default.hex}}"
purple     = "{{colors.tertiary.default.hex}}"

# Container
card_bg    = "{{colors.secondary_container.default.hex}}"
on_card    = "{{colors.on_secondary_container.default.hex}}"

# Utility
outline    = "{{colors.outline.default.hex}}"

# Completion
c.colors.completion.fg                          = fg
c.colors.completion.odd.bg                      = bg
c.colors.completion.even.bg                     = surface
c.colors.completion.category.fg                 = accent
c.colors.completion.category.bg                 = surface_hi
c.colors.completion.category.border.top         = surface_hi
c.colors.completion.category.border.bottom      = outline
c.colors.completion.item.selected.fg            = on_accent
c.colors.completion.item.selected.bg            = accent
c.colors.completion.item.selected.border.top    = accent
c.colors.completion.item.selected.border.bottom = accent
c.colors.completion.match.fg                    = accent
c.colors.completion.scrollbar.fg                = fg_dim
c.colors.completion.scrollbar.bg                = surface_hi

# Downloads bar
c.colors.downloads.bar.bg   = bg
c.colors.downloads.start.fg = on_accent
c.colors.downloads.start.bg = accent
c.colors.downloads.stop.fg  = on_card
c.colors.downloads.stop.bg  = card_bg
c.colors.downloads.error.fg = red

# Hints (link-follow overlay)
c.colors.hints.fg       = on_accent
c.colors.hints.bg       = accent
c.colors.hints.match.fg = on_accent

# Key hint overlay
c.colors.keyhint.fg        = fg
c.colors.keyhint.bg        = surface_hi
c.colors.keyhint.suffix.fg = accent

# Messages
c.colors.messages.error.bg      = red
c.colors.messages.error.border  = red
c.colors.messages.error.fg      = on_red
c.colors.messages.warning.bg     = red_ctr
c.colors.messages.warning.border = red_ctr
c.colors.messages.warning.fg     = fg
c.colors.messages.info.bg        = surface_hi
c.colors.messages.info.border    = surface_hi
c.colors.messages.info.fg        = fg

# Prompts
c.colors.prompts.bg          = surface_hi
c.colors.prompts.border      = f"1px solid {accent}"
c.colors.prompts.fg          = fg
c.colors.prompts.selected.bg = accent
c.colors.prompts.selected.fg = on_accent

# Status bar
c.colors.statusbar.normal.bg           = bg
c.colors.statusbar.normal.fg           = fg
c.colors.statusbar.insert.bg           = accent
c.colors.statusbar.insert.fg           = on_accent
c.colors.statusbar.passthrough.bg      = purple
c.colors.statusbar.passthrough.fg      = on_accent
c.colors.statusbar.private.bg          = card_bg
c.colors.statusbar.private.fg          = on_card
c.colors.statusbar.command.bg          = surface_hi
c.colors.statusbar.command.fg          = fg
c.colors.statusbar.command.private.bg  = card_bg
c.colors.statusbar.command.private.fg  = on_card
c.colors.statusbar.caret.bg            = purple
c.colors.statusbar.caret.fg            = on_accent
c.colors.statusbar.caret.selection.bg  = purple
c.colors.statusbar.caret.selection.fg  = on_accent
c.colors.statusbar.progress.bg         = accent
c.colors.statusbar.url.fg              = fg
c.colors.statusbar.url.error.fg        = red
c.colors.statusbar.url.hover.fg        = accent
c.colors.statusbar.url.success.http.fg  = warn
c.colors.statusbar.url.success.https.fg = accent
c.colors.statusbar.url.warn.fg          = warn

# Tabs
c.colors.tabs.bar.bg                  = surface
c.colors.tabs.odd.fg                  = fg
c.colors.tabs.odd.bg                  = surface
c.colors.tabs.even.fg                 = fg
c.colors.tabs.even.bg                 = bg
c.colors.tabs.selected.odd.fg         = on_accent
c.colors.tabs.selected.odd.bg         = accent
c.colors.tabs.selected.even.fg        = on_accent
c.colors.tabs.selected.even.bg        = accent
c.colors.tabs.pinned.odd.fg           = fg
c.colors.tabs.pinned.odd.bg           = surface
c.colors.tabs.pinned.even.fg          = fg
c.colors.tabs.pinned.even.bg          = bg
c.colors.tabs.pinned.selected.odd.fg  = on_accent
c.colors.tabs.pinned.selected.odd.bg  = accent
c.colors.tabs.pinned.selected.even.fg = on_accent
c.colors.tabs.pinned.selected.even.bg = accent
