color={{colors.background.default.hex_stripped}}
font=FiraMono Nerd Font
font-size=16
indicator-radius=80
indicator-thickness=8
line-color={{colors.background.default.hex_stripped}}
ring-color={{colors.primary.default.hex_stripped}}
inside-color={{colors.surface_variant.default.hex_stripped}}
key-hl-color={{colors.primary.default.hex_stripped}}
separator-color=00000000
text-color={{colors.on_background.default.hex_stripped}}
bs-hl-color={{colors.error.default.hex_stripped}}
ring-wrong-color={{colors.error.default.hex_stripped}}
text-wrong-color={{colors.error.default.hex_stripped}}
inside-wrong-color={{colors.surface_variant.default.hex_stripped}}
line-wrong-color={{colors.error.default.hex_stripped}}
inside-clear-color={{colors.surface_variant.default.hex_stripped}}
text-clear-color={{colors.on_background.default.hex_stripped}}
ring-clear-color={{colors.primary.default.hex_stripped}}
line-clear-color={{colors.background.default.hex_stripped}}
show-failed-attempts=true
