set preview_images true
set preview_images_method kitty
set use_preview_script true
set preview_script ~/.config/ranger/scope.sh
set vcs_aware true

# Keybindings
map e edit
map i display_file
map E shell nvim -- "$@"

# Settings
set line_numbers relative
set confirm_on_delete multiple
