# Org Mode files
ext org, has nvim = nvim -- "$@"
ext org, has editor = "$EDITOR" -- "$@"

# Fallbacks for text files
mime ^text,  has nvim = nvim -- "$@"
mime ^text,  has editor = "$EDITOR" -- "$@"
!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php|nix|glsl|kbd = nvim -- "$@"

# Fallback for everything else to try and open in nvim if no other match
# (Note: Rifle stops at the first match that succeeds)
label editor = nvim -- "$@"
label pager  = "$PAGER" -- "$@"
