# GLava — OpenGL audio spectrum visualizer (runs via XWayland).
# Colors generated by matugen into ~/.config/glava/bars.glsl.
# Toggle on/off with Mod+Ctrl+G (bound in niri binds.kdl).
{
  pkgs,
  dotfilesDir,
  ...
}: let
  toggleGlava = pkgs.writeShellApplication {
    name = "toggle-glava";
    runtimeInputs = with pkgs; [libnotify procps glava];
    text = ''
      if pgrep -x glava > /dev/null; then
        pkill -x glava
        notify-send -t 2000 "GLava" "Disabled"
      else
        glava &
        disown
        notify-send -t 2000 "GLava" "Enabled"
      fi
    '';
  };
in {
  home.packages = [
    pkgs.glava
    toggleGlava
  ];

  # Static main config — module selection, window behavior, audio source.
  xdg.configFile."glava/rc.glsl".source = dotfilesDir + "/glava/rc.glsl";

  # bars.glsl is written by matugen to ~/.config/glava/bars.glsl (see config.toml).
  # Linking individual files (not the whole dir) so matugen can write alongside.
}
