# Centralized keyboard layout mapping — Neovim + Qutebrowser generators.
#
# Imports layout data from keymap-layouts.nix (single source of truth) and
# generates format-specific config fragments so keybindings work regardless
# of active keyboard layout.
#
# QuickShell generation lives in quickshell.nix (it imports keymap-layouts.nix
# directly because it needs to bundle the output into its own runCommand).
#
# To add a new language:  edit keymap-layouts.nix, rebuild.
# To add a new app:       write a generator here (or in the app's module)
#                          that consumes keymap-layouts.nix.
{
  pkgs,
  lib,
  dotfilesDir,
  ...
}: let
  layouts = import ./keymap-layouts.nix;

  # ── Helpers ──────────────────────────────────────────────────────────────

  # Flatten all layouts into a list of { from, to } pairs.
  allPairs = lib.concatLists (lib.mapAttrsToList (_name: layout:
    (lib.mapAttrsToList (from: to: {inherit from to;}) layout.lower)
    ++ (lib.mapAttrsToList (from: to: {inherit from to;}) layout.upper)
    ++ (lib.mapAttrsToList (from: to: {inherit from to;}) layout.punctuation.lower)
    ++ (lib.mapAttrsToList (from: to: {inherit from to;}) layout.punctuation.upper))
  layouts);

  # Escape a character for Vim's langmap option embedded in a Lua "..." string.
  # Two layers: (1) Vim langmap needs \, and \; for its delimiters, and \\ for
  # literal backslash.  (2) The Lua double-quoted string needs \ and " escaped.
  # The Nix string adds a third layer of escaping at write time.
  #
  # Resulting file content per special character:
  #   , → \\,    (Lua reads \\, → \,  ; Vim reads \,  → literal ,)
  #   ; → \\;    (Lua reads \\; → \;  ; Vim reads \;  → literal ;)
  #   \ → \\\\   (Lua reads \\\\ → \\ ; Vim reads \\ → literal \)
  #   " → \"     (Lua reads \" → "    ; Vim sees literal ")
  vimEscape = c:
    if c == "\\"
    then "\\\\\\\\"
    else if c == ","
    then "\\\\,"
    else if c == ";"
    then "\\\\;"
    else if c == "\""
    then "\\\""
    else c;

  # Python single-quoted string escaping.
  pyEscape = c:
    if c == "'"
    then "\\'"
    else if c == "\\"
    then "\\\\"
    else c;

  # ── Neovim: langmap.lua ─────────────────────────────────────────────────
  # Maps non-Latin → Latin for normal/visual/operator-pending mode.
  # Insert mode is unaffected.

  langmapEntries = lib.concatStringsSep "," (map (p: "${vimEscape p.from}${vimEscape p.to}") allPairs);

  vimLangmapLua = ''
    -- Generated by modules/home/core/keymap.nix — do not edit.
    -- Maps non-Latin characters to Latin equivalents for normal/visual/
    -- operator-pending mode so keybindings work regardless of active layout.
    vim.opt.langmap = "${langmapEntries}"
  '';

  # ── Qutebrowser: keymap.py ─────────────────────────────────────────────
  # Maps non-Latin → Latin so all default and custom keybindings work
  # when a non-Latin layout is active.

  pyEntries = lib.concatStringsSep "\n" (map (p: "    '${pyEscape p.from}': '${pyEscape p.to}',") allPairs);

  qutebrowserKeymapPy = ''
    # Generated by modules/home/core/keymap.nix — do not edit.
    # Maps non-Latin keys to Latin equivalents so keybindings work
    # regardless of active keyboard layout.
    c.bindings.key_mappings = {
    ${pyEntries}
    }
  '';

  # ── Neovim: hybrid runCommand ───────────────────────────────────────────
  # Copies raw nvim dotfiles and injects the generated langmap.lua.

  nvimConfig = pkgs.runCommand "nvim-config" {} ''
    mkdir -p $out/lua/ovg
    cp ${dotfilesDir}/nvim/init.lua                $out/init.lua
    cp ${dotfilesDir}/nvim/lua/ovg/remap.lua       $out/lua/ovg/remap.lua
    cp ${dotfilesDir}/nvim/lua/ovg/plugins.lua     $out/lua/ovg/plugins.lua
    cp ${dotfilesDir}/nvim/lua/ovg/highlights.lua  $out/lua/ovg/highlights.lua
    cp ${dotfilesDir}/nvim/lua/ovg/lualine_theme.lua $out/lua/ovg/lualine_theme.lua
    cp ${pkgs.writeText "langmap.lua" vimLangmapLua}  $out/lua/ovg/langmap.lua
  '';
in {
  # Neovim — hybrid: raw dotfiles + generated langmap.lua
  xdg.configFile."nvim".source = lib.mkForce nvimConfig;

  # Qutebrowser — generated keymap sourced by the raw config.py
  xdg.configFile."qutebrowser/keymap.py".text = qutebrowserKeymapPy;
}
