-- Lualine theme: colors generated by matugen from the current wallpaper palette.
-- Gradient rule: a.bg (accent, lightest) → b (surface mid) → c.bg (surface, darkest).
-- Regenerated at: ~/.cache/matugen/nvim-lualine.lua  (on every wallpaper change).
-- Live-reloaded via SIGUSR1 (see highlights.lua).
local cache = vim.fn.expand("~/.cache/matugen/nvim-lualine.lua")
if vim.fn.filereadable(cache) == 1 then
  return dofile(cache)
end
-- Fallback: let lualine use its built-in default until matugen has run once.
return "auto"
